config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  
  devise_for :users
  root to: 'home#index'
  resources :projects
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_one :client
  has_one :freelancer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :project
  belongs_to :client
  belongs_to :freelancer
  validates :description, :presence => true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :account
  has_many :projects
  has_many :contracts
  has_many :bids
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :client
  belongs_to :freelancer
  has_one :contract
  validates :price, :presence => true
end

app/models/freelancer.rb
class Freelancer < ApplicationRecord
  belongs_to :account
  has_many :bids
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :client
  has_many :bids
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :name
  has_one :account

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :create_new_account

  def create_new_account
    self.create_account(:name => @name)
    self.account.create_client()
    self.account.create_freelancer()
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :current_client, :current_freelancer

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?



  def current_client
    current_user.account.client
  end

  def current_freelancer
    current_user.account.freelancer
  end

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :avatar) }
  end
end

app/controllers/bid_controller.rb
class BidController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = current_user
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @project = Project.new()
  end

  def create
    
  end

  def index
    @projects = Project.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bid_helper.rb
module BidHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/bid/create.html.erb
<h1>Bid#create</h1>
<p>Find me in app/views/bid/create.html.erb</p>

app/views/bid/new.html.erb
<h1>Bid#new</h1>
<p>Find me in app/views/bid/new.html.erb</p>

app/views/home/index.html.erb
<% if current_user %>
  <h1>Freaky <%= current_user.account.name%>!</h1>
<% end %>

app/views/layouts/_navigation.html.erb
<h1>the BidNiz . com</h1>
<% if !current_user %>
  <%= link_to "SIGN UP", new_user_registration_path %>
  <%= link_to "SIGN IN", new_user_session_path %>
<% end %>
<% if current_user %>
  Hello, <%=current_user.account.name %>
  <%= link_to "SIGN OUT", destroy_user_session_path, :method => :delete %>
  <%= link_to "NEW PROJECT", new_project_path %>
<% end %>
<a href="/">HOME</a>
<%= link_to "PROJECTS", projects_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thebidniz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <%= yield %>
  </body>
</html>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/index.html.erb
<h1>PROJECTS</h1>
<% if @projects.any? %>
  <%= @projects.each do |project| %>

    <p>Hello<%= project.title %></p>
  <% end %>
<% end %>

app/views/projects/new.html.erb
<h1>NEW PROJECT</h1>
<%= form_for @project do |f| %>


  <div class="form-group">
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.cktext_area :details, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>